# This file can be used for very simple installation that uses
# insecure urls (i.e. http, not httpS). This may not be be allowed in some environments
# and/or your browser may give a security warning
# Excellent choice for 1st time ISD Trial
#
# Instructions:
# a) Update the 3 URLs below
# b) Update the git repo details
# c) Follow the installation instructions to experience the next generation of Software Delivery
#
global:
  createIngress: true 
  gitea:
   enabled: false
  certManager:
    installed: false
  ssl:
    enabled: false
  spinDeck:
    protocol: http
    host: spin.oes.opsmx.net   # REPLACE if you have DNS access, else use hosts file entries
  ## OES-UI url configuration
  oesUI:
    protocol: http
    host: oes.oes.opsmx.net    # REPLACE if you have DNS access, else use hosts file entries
  ## OES-Gate url configuration
  oesGate:
    protocol: http
    host: oes-gate-ldap.oes.opsmx.net # REPLACE if you have DNS access, else use hosts file entries

spinnaker:
  gitopsHalyard:
    enabled: true
    repo:
      organization: 101781958  # REPLACE
      username: IArshidinova    # REPLACE
      token: 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     # REPLACE
      repository: test   # REPLACE repo name for GitOps Halyard (Sample Reference: https://github.com/OpsMx/sample-gitops-repo.git).
      dynamicAccRepository: test # REPLACE Please provide the repo name of the GitOps Dynamic Accounts Directory
